[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
installCommand = "npm install --legacy-peer-deps"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/"
timeout = 100
